/* USER */
export const LOGOUT = 'LOG_OUT'
export const LOGGING_IN = 'LOGGING_IN'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const REGISTERING = 'REGISTERING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const UPDATING_ACCOUNT = "UPDATING_ACCOUNT"
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS"
export const UPDATE_ACCOUNT_FAILED = "UPDATE_ACCOUNTY_FAILED"  

export const AUTH_RESET = 'AUTH_RESET'

/* APP */
export const LOAD_APP = 'LOAD_APP'

/* CATEGORY */
export const FECTHING_CATEGORIES = 'FECTHING_CATEGORIES'
export const FETCHED_CATEGORIES = 'FETCHED_CATEGORIES'

/* ACTIVITY */
export const FETCHING_ACTIVITIES = 'FETCHING_ACTIVITIES'
export const FETCH_ACTIVITIES_FAILED = 'FETCHING_ACTIVITIES_FAILED'
export const FETCH_ACTIVITIES_SUCCESS = 'FETCHING_ACTIVITIES_SUCCESS'

export const CREATING_ACTIVITY = 'CREATING_ACTIVITY'
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS'
export const CREATE_ACTIVITY_FAILED = 'CREATE_ACTIVITY_FAILED'

export const UPDATING_ACTIVITY = "UPDATING_ACTIVITY"
export const UPDATE_ACTIVITY_SUCCESS = "UPDATE_ACTIVITY_SUCCESS"
export const UPDATE_ACTIVITY_FAILED = "UPDATE_ACTIVITY_FAILED"  

export const UPLOADING_PHOTOS = "UPLOADING_PHOTO"
export const UPLOAD_PHOTOS_SUCCESS = "UPLOAD_PHOTOS_SUCCESS"
export const UPLOAD_PHOTOS_FAILED = "UPLOAD_PHOTOS_FAILED"  

export const ACTIVITY_RESET = "ACTIVITY_RESET"