/* USER */
export const LOGOUT = 'LOG_OUT'
export const LOGGING_IN = 'LOG_IN'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const REGISTERING = 'REGISTERING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const AUTH_RESET = 'AUTH_RESET'

/* CATEGORY */
export const FECTHING_CATEGORIES = 'FECTHING_CATEGORIES'
export const FETCHED_CATEGORIES = 'FETCHED_CATEGORIES'

/* ACTIVITY */
export const FETCHING_ACTIVITIES = 'FETCHING_ACTIVITIES'
export const FETCH_ACTIVITIES_FAILED = 'FETCHING_ACTIVITIES_FAILED'
export const FETCH_ACTIVITIES_SUCCESS = 'FETCHING_ACTIVITIES_SUCCESS'
export const CREATING_ACTIVITY = 'CREATING_ACTIVITY'
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS'
export const CREATE_ACTIVITY_FAILED = 'CREATE_ACTIVITY_FAILED'